language: php

sudo: false

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit

jobs:
  include:
    - stage: Code quality
      php: 7.2
      script:
        - ./vendor/bin/phpcs
        - ./vendor/bin/psalm
      git:
        submodules: false

cache:
  directories:
    - vendor
    - $HOME/.cache/composer