#!/usr/bin/env php
<?php

declare(strict_types=1);

use Babelfish\Internal\Generator\Alias;
use Babelfish\Internal\DataDumper;
use Babelfish\Internal\Dump;
use Babelfish\Internal\Generator\ClassifierSample;
use Babelfish\Internal\Generator\Extension;
use Babelfish\Internal\Generator\Filename;
use Babelfish\Internal\Generator\Heuristic;
use Babelfish\Internal\Generator\Interpreter;

require_once __DIR__ . '/../vendor/autoload.php';

$yaml_parser = new \Babelfish\Internal\Parser\Yaml;

$data_dumper = new DataDumper(
    new Dump(
        __DIR__ . '/../src/Babelfish/Data/Aliases.php',
        new Alias('lib/linguist/languages.yml', $yaml_parser)
    ),
    new Dump(
        __DIR__ . '/../src/Babelfish/Data/Filenames.php',
        new Filename('lib/linguist/languages.yml', $yaml_parser)
    ),
    new Dump(
        __DIR__ . '/../src/Babelfish/Data/Interpreters.php',
        new Interpreter('lib/linguist/languages.yml', $yaml_parser)
    ),
    new Dump(
        __DIR__ . '/../src/Babelfish/Data/Extensions.php',
        new Extension('lib/linguist/languages.yml', $yaml_parser)
    ),
    new Dump(
        __DIR__ . '/../src/Babelfish/Data/Heuristics.php',
        new Heuristic('lib/linguist/heuristics.yml', $yaml_parser)
    ),
    new Dump(
        __DIR__ . '/../src/Babelfish/Data/ClassifierSamples.php',
        new ClassifierSample
    )
);
$data_dumper->dump(__DIR__ . '/../linguist/');