#!/usr/bin/env php
<?php

declare(strict_types=1);

use Babelfish\Internal\AliasGenerator;
use Babelfish\Internal\DataDumper;
use Babelfish\Internal\Dump;
use Babelfish\Internal\FilenameGenerator;

require_once __DIR__ . '/../vendor/autoload.php';

$data_dumper = new DataDumper(
    new Dump(
        __DIR__ . '/../src/Babelfish/Data/Aliases.php',
        new AliasGenerator
    ),
    new Dump(
        __DIR__ . '/../src/Babelfish/Data/Filenames.php',
        new FilenameGenerator
    )
);
$data_dumper->dump(__DIR__ . '/../linguist/');