name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']
        dependencies: ['', '--prefer-lowest --prefer-stable']
    name: Tests on PHP ${{ matrix.php-versions }} ${{ matrix.dependencies }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --depth=1
      - uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php-versions }}
          extension: mbstring
          coverage: pcov
      - name: Remove Composer lockfile
        run: rm composer.lock
      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist ${{ matrix.dependencies }}
      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
  code_quality:
    runs-on: ubuntu-18.04
    name: Code quality
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: shivammathur/setup-php@2.15.0
        with:
          php-version: '7.4'
          extension: mbstring
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction
      - name: PHPCS
        run: ./vendor/bin/phpcs
      - name: Psalm
        run: ./vendor/bin/psalm --shepherd
